# Generated by Django 4.0.4 on 2022-06-10 12:28

from django.db import migrations, models
import static_content.utils


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=static_content.utils.upload_to),
        ),
    ]
